<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_groupSettings</name>
   <tag></tag>
   <elementGuidId>6802f387-b747-4254-9559-c70281056577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;c c--campus c--g person--logged-true c--contexts-true&quot;]/div[2]/div[@class=&quot;c-wrapper row&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header--group&quot;]/div[@class=&quot;header-menu&quot;]/div[@class=&quot;header-menu__navigation&quot;]/div[@class=&quot;group-button&quot;]/div[@class=&quot;has-flyout group-cog&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div[2]/div[1]/header/div/div[2]/div[1]/div/div
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-cog cog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flyout-id</name>
      <type>Main</type>
      <value>flyout-group-card-cog-d0133678-5f66-4b0d-89c0-217141abb630</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;c c--campus c--g person--logged-true c--contexts-true&quot;]/div[2]/div[@class=&quot;c-wrapper row&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;header--group&quot;]/div[@class=&quot;header-menu&quot;]/div[@class=&quot;header-menu__navigation&quot;]/div[@class=&quot;group-button&quot;]/div[@class=&quot;has-flyout group-cog&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/header/div/div[2]/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
